### ISSUE TITLE
If I need a new scenario should I include this repo in my project?

### ISSUE THREAD

**Issue by protoEvangelion** [octokit/fixtures#149]
@gr2m  What I am trying to figure out is how to version control a new scenario if it is not included in @octokit/fixtures.

In the next couple weeks, I will be writing several new scenarios for https://github.com/node-gh/gh/. Would you recommend including your repo in my project to create new scenarios or just send you a PR with the new scenarios? 

By the way I am learning a lot from this project. Fantastic work!

**Comment by gr2m** [comment]
Hey Ryan! I’m so sorry for the late response, recent family expansion is keeping me busy :) 

I’d love to collaborate! For now let's add scenarios here, but eventually I’d be up to make this repository more flexible, maybe split it up into a recorder and fixtures

Thanks for the kind word :)

**Comment by protoEvangelion** [comment]
@gr2m Thanks much for the response! I will go ahead and send you PRs then.
