### ISSUE TITLE
Many devDependencies should be (production) dependencies

### ISSUE THREAD

**Issue by AArnott** [octokit/fixtures#335]
I just installed `@octokit/fixtures` into my packages.json file as a `devDependencies` so that I can write tests that mock up my octokit calls. But when I try to record a scenario:

```
node node_modules/@octokit/fixtures/bin/record.js api.github.com/get-pr
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'bottleneck'
Require stack:
- /home/andrew/git/pr-autocomplete-app/node_modules/@octokit/fixtures/bin/record.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/andrew/git/pr-autocomplete-app/node_modules/@octokit/fixtures/bin/record.js:13:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/andrew/git/pr-autocomplete-app/node_modules/@octokit/fixtures/bin/record.js'
  ]
}
```

I get errors because `@octokit/fixtures` requires a lot of node_modules that are not present. Dependencies such as these:

https://github.com/octokit/fixtures/blob/0ac99e9b41b30d9e44951838747191e9aee40fa8/package.json#L44-L47

Given these dependencies are required at runtime by your package's consumers, these are not `devDependencies`, right? They should be under `dependencies` so that when I install your package, npm will also give me all the dependencies that your package needs at runtime.

**Comment by gr2m** [comment]
the record feature is not meant to be used by consumers, only the mocks. Interesting thought though

You could record your fixtures directly into `@octokit/fixtures` and submit a pull request, so everyone could benefit?

**Comment by AArnott** [comment]
Oh! Interesting. I didn't catch from the README that we weren't supposed to record our own scenarios. Some of the scenarios I need to mock up are mutating calls (e.g. completing a PR). How would those be recorded and then re-tested the next day as your docs indicate happen daily without invalidating the test itself by the mutation?
Or, if such mutating recordings are out of scope of your goals here, do you have any recommendations for how I can do it myself? I don't need to update daily (although that's a neat system that we'd benefit from if we could manage it).

**Comment by gr2m** [comment]
> Some of the scenarios I need to mock up are mutating calls (e.g. completing a PR). How would those be recorded and then re-tested the next day as your docs indicate happen daily without invalidating the test itself by the mutation

Give it a try :) Most of the scenarios in this repositories are multi-request scenarios with mutations, too. There is a lot of normalization going on which keeps the recorded fixtures the same, by normalizing IDs, timestamps, etc

**Comment by gr2m** [comment]
I really like the idea of allowing everyone to record own fixtures, e.g. using a reusable GitHub Action. The resulting fixtures could then be shared again, for others to use.

But for now, I'd suggest to just add a pull request to octokit/fixtures. Make sure to check out https://github.com/octokit/fixtures/blob/master/HOW_IT_WORKS.md and https://github.com/octokit/fixtures/blob/master/CONTRIBUTING.md

**Comment by AArnott** [comment]
Thanks for the ideas. For now, I've just used `nock` directly to mock up Octokit as that was more straightforward than figuring out how to record and replay scenarios, or even playback the prerecorded scenarios.

**Comment by gr2m** [comment]
I'll close the issue because there is nothing actionable at this point. I'm still very interested in permitting others to record their own fixtures. I'll keep you posted if there are any news in that regard. Please let me know if you are interested in collaborating on that
